version: '3'
services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  server:    
    build: ./api
    restart: always
    container_name: server
    depends_on:
      - mongo
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Docker
  web:
    build: ./web
    restart: always
    container_name: web
    depends_on:
      - server
    ports:
      - "4200:80"    